"""Derive the SignalRGB K70 MAX layout from mac-agent/k70max_layout.h.

The C++ header is the single source of truth for the keyboard geometry: 142
hardware channels, 116 of which have a physical LED, each with a normalized
x/y. SignalRGB instead wants integer canvas cells, so this script projects
those coordinates onto a grid and emits the three tables the plugin needs:

    LED_NAMES       116 labels
    LED_POSITIONS   116 [col, row] cells, all distinct
    LED_WIRE_INDEX  116 indices into the 142-slot wire frame

Run it whenever the header changes:

    python tools/gen_k70_layout.py --check          # verify the plugin is current
    python tools/gen_k70_layout.py --write          # rewrite the plugin block
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from headless_lights.k70max import (  # noqa: E402  (needs the path above)
    HEADER_PATH,
    WIRE_SLOTS,
    LayoutError,
    parse_header,
)

PLUGIN_PATH = REPO_ROOT / "signalrgb" / "headless-lights-mac.js"

GRID_WIDTH = 22

BEGIN_MARKER = "// BEGIN GENERATED K70 LAYOUT"
END_MARKER = "// END GENERATED K70 LAYOUT"


def _rows(mapped: list[tuple[int, float, float]]) -> list[float]:
    """Distinct y values, ascending. Each becomes one canvas row.

    The K70 MAX has seven key rows plus two light bar LEDs sitting between
    them; giving every distinct y its own row keeps those two off the key grid
    instead of fighting for a cell with a real key.
    """
    return sorted({round(y, 6) for _, _, y in mapped})


def build_layout(
    entries: list[tuple[float, float, bool]],
    *,
    width: int = GRID_WIDTH,
) -> tuple[list[str], list[list[int]], list[int], list[int]]:
    mapped = [
        (index, x, y)
        for index, (x, y, is_mapped) in enumerate(entries)
        if is_mapped
    ]
    rows = _rows(mapped)

    placements: dict[int, tuple[int, int]] = {}
    for row, row_y in enumerate(rows):
        members = sorted(
            ((x, index) for index, x, y in mapped if round(y, 6) == row_y),
        )
        # Walk the row left to right, keeping the physical order: each key takes
        # its rounded column unless a neighbour already claimed it.
        previous = -1
        columns: list[int] = []
        for x, _ in members:
            column = max(round(x * (width - 1)), previous + 1)
            columns.append(column)
            previous = column
        if columns and columns[-1] > width - 1:
            # Relax backwards so the row fits, preserving order.
            limit = width - 1
            for position in range(len(columns) - 1, -1, -1):
                columns[position] = min(columns[position], limit)
                limit = columns[position] - 1
            if columns[0] < 0:
                raise LayoutError(
                    f"row {row} has {len(columns)} LEDs and cannot fit in {width} columns"
                )
        for (_, index), column in zip(members, columns):
            placements[index] = (column, row)

    wire_index = sorted(placements)
    positions = [[placements[index][0], placements[index][1]] for index in wire_index]
    names = [
        f"R{placements[index][1]}C{placements[index][0]}" for index in wire_index
    ]

    if len(set(map(tuple, positions))) != len(positions):
        raise LayoutError("two LEDs landed on the same canvas cell")

    return names, positions, wire_index, [width, len(rows)]


def render_block(
    names: list[str],
    positions: list[list[int]],
    wire_index: list[int],
    size: list[int],
) -> str:
    def wrap(values: list[str], per_line: int) -> str:
        lines = []
        for start in range(0, len(values), per_line):
            lines.append("\t" + " ".join(values[start : start + per_line]))
        return "\n".join(lines)

    names_text = wrap([f'"{name}",' for name in names], 8)
    positions_text = wrap([f"[{col},{row}]," for col, row in positions], 8)
    wire_text = wrap([f"{index}," for index in wire_index], 16)

    return (
        f"{BEGIN_MARKER}\n"
        f"// Generated by tools/gen_k70_layout.py from mac-agent/k70max_layout.h.\n"
        f"// Do not edit by hand; edit the header and regenerate.\n"
        f"const K70_SIZE = [{size[0]}, {size[1]}];\n"
        f"const K70_WIRE_SLOTS = {WIRE_SLOTS};\n"
        f"const K70_LED_NAMES = [\n{names_text}\n];\n"
        f"const K70_LED_POSITIONS = [\n{positions_text}\n];\n"
        f"const K70_WIRE_INDEX = [\n{wire_text}\n];\n"
        f"{END_MARKER}"
    )


def splice(plugin_text: str, block: str) -> str:
    start = plugin_text.find(BEGIN_MARKER)
    end = plugin_text.find(END_MARKER)
    if start < 0 or end < 0:
        raise LayoutError(
            f"{PLUGIN_PATH.name} is missing the {BEGIN_MARKER} / {END_MARKER} markers"
        )
    return plugin_text[:start] + block + plugin_text[end + len(END_MARKER) :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="gen_k70_layout")
    action = parser.add_mutually_exclusive_group()
    action.add_argument(
        "--write", action="store_true", help="rewrite the generated block in the plugin"
    )
    action.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the plugin block is out of date",
    )
    args = parser.parse_args(argv)

    entries = parse_header(HEADER_PATH.read_text(encoding="utf-8"))
    names, positions, wire_index, size = build_layout(entries)
    block = render_block(names, positions, wire_index, size)

    if not args.write and not args.check:
        print(block)
        return 0

    plugin_text = PLUGIN_PATH.read_text(encoding="utf-8")
    updated = splice(plugin_text, block)
    if args.check:
        if updated != plugin_text:
            print(
                f"{PLUGIN_PATH} is out of date; run tools/gen_k70_layout.py --write",
                file=sys.stderr,
            )
            return 1
        print(f"{PLUGIN_PATH.name} is up to date")
        return 0

    PLUGIN_PATH.write_text(updated, encoding="utf-8")
    print(f"updated {PLUGIN_PATH} with {len(names)} LEDs on a {size[0]}x{size[1]} grid")
    return 0


if __name__ == "__main__":
    sys.exit(main())
