"""Derive our Corsair Bragi fork from the plugin SignalRGB ships, and install it.

SignalRGB's own Corsair_Bragi_Device.js already decodes the Scimitar's side
buttons, but hands them to a macro engine whose binding UI does not load in
2.5.74, so the presses reach nothing. Our fork is that plugin with the buttons
wired to real Windows virtual keys instead, claiming the Slipstream dongle alone
so every other Corsair device keeps the stock plugin.

Copying 4000 lines by hand would rot on the first SignalRGB update. This applies
the difference as anchored edits instead: an update either still matches every
anchor, or this fails and names the one that moved.

Installing it has one hard constraint, established by watching the crawler's
log. SignalRGB keeps three plugin sources and the last one to claim a VID:PID
wins. Add-ons added by URL are crawled *before* the stock plugins, so an add-on
cannot override one -- ours registered 1b1c:2b00 and the shipped Corsair plugin
immediately took it back. The app's own Plugins folder is crawled after, and
does win, so that is where this installs. An app update replaces that folder,
which is what --install is for.

    python tools/vendor_bragi.py             # regenerate the fork
    python tools/vendor_bragi.py --check     # fail if it is out of date
    python tools/vendor_bragi.py --install   # regenerate and install it
    python tools/vendor_bragi.py --uninstall # remove it again
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import sys


REPO_ROOT = Path(__file__).resolve().parents[1]
FORK = REPO_ROOT / "signalrgb" / "corsair-bragi-scimitar.js"
UPSTREAM_RELATIVE = Path(
    "Signal-x64/Plugins/Corsair/Modern_Corsair/Corsair_Bragi_Device.js"
)
# Installed at the top of the app's plugin tree, under a name that sorts after
# the Corsair folder the stock plugin lives in.
INSTALLED_NAME = "ZZZ_Corsair_Bragi_Scimitar.js"

SLIPSTREAM_PID = 0x2B00
SIDE_BUTTON_COUNT = 12

# Label -> Windows virtual-key code, offered in every side-button combobox.
# "None" swallows the press; "SignalRGB macro" is deliberately absent from the
# table so it falls through to the stock macro event.
DIGITS = [(str(digit), 0x30 + digit) for digit in range(1, 10)] + [("0", 0x30)]
OEM = [("-", 0xBD), ("=", 0xBB)]
FUNCTION_KEYS = [(f"F{13 + index}", 0x7C + index) for index in range(12)]
NUMPAD = [(f"Numpad {digit}", 0x60 + digit) for digit in range(10)]
VIRTUAL_KEYS = [("None", 0x00)] + DIGITS + OEM + FUNCTION_KEYS + NUMPAD
FALLTHROUGH = "SignalRGB macro"

# Button N defaults to the key the macOS agent already injects for it, so the
# mouse behaves the same on both sides of the USB-C switch.
DEFAULTS = [label for label, _ in DIGITS + OEM]


def banner() -> str:
    return """// Corsair Bragi devices, with the Scimitar's side buttons restored.
//
// Generated by tools/vendor_bragi.py from the Corsair_Bragi_Device.js that
// SignalRGB installs, which is WhirlwindFX's work. Do not edit this file by
// hand: edit the patch in that script and regenerate, or the next SignalRGB
// update silently reverts the change.
//
// Two differences from upstream, both outside the lighting path:
//
//   * it claims the Slipstream dongle alone, so every other Corsair device
//     keeps the stock plugin;
//   * a side-button press becomes a Windows virtual key, chosen per button in
//     the device's settings, instead of a macro event that 2.5.74 drops on the
//     floor.
"""


def parameter_lines() -> str:
    """The twelve side-button comboboxes, in the style of the parameters above."""
    values = ", ".join(
        f'"{label}"'
        for label in [label for label, _ in VIRTUAL_KEYS[1:]] + ["None", FALLTHROUGH]
    )
    lines = []
    for index in range(SIDE_BUTTON_COUNT):
        number = index + 1
        lines.append(
            f'\t\t{{"property":"sideButton{number}", "group":"side buttons", '
            f'"label":"Side Button {number}", '
            f'description: "The key this side button sends. '
            f'\'None\' ignores the button; \'{FALLTHROUGH}\' hands it to '
            f'SignalRGB\'s macro engine instead", '
            f'"type":"combobox", "values":[{values}], '
            f'"default":"{DEFAULTS[index]}"}},'
        )
    return "\n".join(lines)


def side_button_code() -> str:
    """The helpers the macro path calls, in upstream's tab-indented style."""
    table = "\n".join(
        f'\t"{label}" : 0x{code:02X},' for label, code in VIRTUAL_KEYS
    )
    selections = ", ".join(
        f"sideButton{index + 1}" for index in range(SIDE_BUTTON_COUNT)
    )
    return f"""// Side buttons, added by headless-lights.
//
// In software mode the Scimitar stops sending its twelve side buttons as
// ordinary input and reports them as macro bits instead. Upstream turns those
// into macro events, but the tab that would bind them fails to load in 2.5.74
// ("ThirdpartyMacroTab.qml: '../Macroblocks/': no such directory"), so nothing
// receives them. These send a virtual key directly, the way the media keys and
// the Forward/Back buttons in this file already do.
const sideButtonVirtualKeys = Object.freeze({{
{table}
}});

function sideButtonSelections() {{
\t// Listed one by one because a plugin's settings are plain globals: they are
\t// not reachable through globalThis, so they cannot be looked up by name.
\treturn [{selections}];
}}

function sideButtonVirtualKey(keyName) {{
\tconst match = /^Keypad ([0-9]+)$/.exec(keyName);

\tif(match === null) {{
\t\treturn undefined;
\t}}

\t// Undefined for anything the table does not name, "{FALLTHROUGH}"
\t// included, which leaves the caller on upstream's macro path.
\treturn sideButtonVirtualKeys[sideButtonSelections()[Number(match[1]) - 1]];
}}

"""


def test_seam_code() -> str:
    """The one hook the tests need that the plugin does not already offer."""
    return """// Test seam, added by headless-lights. SignalRGB ignores exports it does not
// know about, so this costs the running plugin nothing.
//
// A report handed to __processInputForTest travels the plugin's own path from
// there on: the notification parsing, the bit diffing, the keymap and our
// virtual keys are all the real thing. Only the child registry is injected,
// because the real one is built by a Bragi handshake that Initialize() holds
// with live hardware, and faking that whole conversation would test the fake
// rather than the plugin.
export function __installMacroSubdeviceForTest(subdeviceID, devicePID) {
\tif(BragiDongle === undefined) {
\t\tBragiDongle = new CorsairBragiDongle();
\t}

\tconst name = CorsairLibrary.ProductIDList()[devicePID];
\tBragiDongle.addChildDevice(subdeviceID, CorsairLibrary.DeviceList()[name], false);
}

export function __processInputForTest(report) {
\tProcessInput(report);
}

"""


def patches() -> list[tuple[str, str]]:
    """(anchor, replacement) pairs; each anchor must appear exactly once."""
    globals_block = "\n".join(
        f"sideButton{index + 1}:readonly" for index in range(SIDE_BUTTON_COUNT)
    )

    return [
        # Claim the Slipstream dongle alone, under a name of our own so the
        # device is recognisable in SignalRGB's list.
        (
            'export function Name() { return "Corsair Bragi Device"; }\n'
            "export function VendorId() { return 0x1b1c; }\n"
            "export function ProductId() { return Object.keys("
            "CorsairLibrary.ProductIDList()); }",
            'export function Name() { return "Corsair Bragi Device '
            '(Scimitar side buttons)"; }\n'
            "export function VendorId() { return 0x1b1c; }\n"
            f"export function ProductId() {{ return [0x{SLIPSTREAM_PID:04x}]; }}",
        ),
        # Declare the new settings to eslint alongside the existing ones.
        (
            "ConnectedFans:readonly\nFanControllerArray:readonly\n*/",
            f"ConnectedFans:readonly\nFanControllerArray:readonly\n"
            f"{globals_block}\n*/",
        ),
        # One combobox per side button, after the lighting parameters.
        (
            '\t\t{"property":"forcedColor", "group":"lighting", "label":'
            '"Forced Color", description: "The color used when \'Forced\' '
            'Lighting Mode is enabled", "min":"0", "max":"360", "type":"color", '
            '"default":"#009bde"},\n\n\t];',
            '\t\t{"property":"forcedColor", "group":"lighting", "label":'
            '"Forced Color", description: "The color used when \'Forced\' '
            'Lighting Mode is enabled", "min":"0", "max":"360", "type":"color", '
            '"default":"#009bde"},\n\n'
            f"{parameter_lines()}\n\t];",
        ),
        # Sending virtual keys needs the keyboard feature, even on a mouse.
        (
            '\tif(deviceConfig.keymapType === "Mouse") {\n'
            '\t\tdevice.addFeature("mouse");\n'
            "\t\tconfigureMouseButtons(deviceID);",
            '\tif(deviceConfig.keymapType === "Mouse") {\n'
            '\t\tdevice.addFeature("mouse");\n'
            "\t\t// The side buttons leave as key presses, which the engine only\n"
            "\t\t// delivers for a device that declares the keyboard feature.\n"
            '\t\tdevice.addFeature("keyboard");\n'
            "\t\tconfigureMouseButtons(deviceID);",
        ),
        # Intercept the side buttons before upstream's macro events.
        (
            "function processMouseMacros(bitIdx, state, keyName) {\n\tif(state) {",
            f"{side_button_code()}"
            "function processMouseMacros(bitIdx, state, keyName) {\n"
            "\tconst virtualKey = sideButtonVirtualKey(keyName);\n"
            "\n"
            "\tif(virtualKey !== undefined) {\n"
            "\t\tif(virtualKey !== 0) {\n"
            "\t\t\tkeyboard.sendHid(virtualKey, {released : !state});\n"
            "\t\t}\n"
            "\n"
            "\t\treturn;\n"
            "\t}\n"
            "\n"
            "\tif(state) {",
        ),
        # Let the tests hand the plugin the subdevice a dongle would report.
        (
            "function processMacroInputs(bitIdx, state) {",
            f"{test_seam_code()}function processMacroInputs(bitIdx, state) {{",
        ),
        # Wire the macro callback at module scope. It needs nothing Initialize()
        # produces, and up here the input path can be exercised by the tests
        # without standing up the whole Bragi handshake.
        (
            "\tfetchAndConfigureChildren();\n"
            "\tmacroInputArray.setCallback((bitIdx, isPressed) => "
            "{ return processMacroInputs(bitIdx, isPressed); });\n}",
            "\tfetchAndConfigureChildren();\n}",
        ),
        (
            "const macroInputArray = new BitArray(32);",
            "const macroInputArray = new BitArray(32);\n"
            "macroInputArray.setCallback((bitIdx, isPressed) => "
            "{ return processMacroInputs(bitIdx, isPressed); });",
        ),
    ]


def find_upstream() -> Path | None:
    """The installed plugin, from whichever of SignalRGB's two copies it has.

    It keeps one inside the app and one in the plugin CDN cache, and refreshes
    the cached one on its own schedule. They are the same file today; if they
    ever diverge, patching the wrong one would produce a fork that quietly does
    not match what the app loads, so that is worth stopping for.
    """
    local = os.environ.get("LOCALAPPDATA")
    if not local:
        return None

    candidates: list[Path] = []
    cached = (
        Path(local)
        / "WhirlwindFX/SignalRgb/cache/plugin_cdn/main"
        / UPSTREAM_RELATIVE.relative_to("Signal-x64")
    )
    if cached.is_file():
        candidates.append(cached)

    installed = []
    for directory in (Path(local) / "VortxEngine").glob("app-*"):
        plugin = directory / UPSTREAM_RELATIVE
        if not plugin.is_file():
            continue
        version = tuple(
            int(part) for part in re.findall(r"\d+", directory.name[len("app-"):])
        )
        installed.append((version, plugin))
    if installed:
        candidates.append(max(installed)[1])

    if not candidates:
        return None

    contents = {
        path.read_text(encoding="utf-8").replace("\r\n", "\n") for path in candidates
    }
    if len(contents) > 1:
        listed = "\n".join(f"  {path}" for path in candidates)
        raise SystemExit(
            "SignalRGB's two copies of the plugin differ:\n"
            f"{listed}\n"
            "Pass the one the app loads with --upstream."
        )
    return candidates[0]


def newest_app() -> Path | None:
    """The newest installed SignalRGB app directory."""
    local = os.environ.get("LOCALAPPDATA")
    if not local:
        return None

    installed = []
    for directory in (Path(local) / "VortxEngine").glob("app-*"):
        if not (directory / "Signal-x64/Plugins").is_dir():
            continue
        version = tuple(
            int(part) for part in re.findall(r"\d+", directory.name[len("app-"):])
        )
        installed.append((version, directory))
    return max(installed)[1] if installed else None


def install_target() -> Path | None:
    """Where the fork has to sit to win the VID:PID over the stock plugin.

    Not the CDN cache, which SignalRGB refreshes from upstream, and not an
    add-on, which is crawled too early to override anything.
    """
    app = newest_app()
    return None if app is None else app / "Signal-x64/Plugins" / INSTALLED_NAME


def render(upstream: Path) -> str:
    """Upstream, normalised to LF, with every patch applied."""
    source = upstream.read_text(encoding="utf-8").replace("\r\n", "\n")

    for anchor, replacement in patches():
        found = source.count(anchor)
        if found != 1:
            head = anchor.splitlines()[0]
            raise SystemExit(
                f"{upstream}: anchor matched {found} times, expected 1.\n"
                f"  starting: {head}\n"
                "  SignalRGB changed this plugin; update the patch in "
                "tools/vendor_bragi.py to match."
            )
        source = source.replace(anchor, replacement)

    if not source.endswith("\n"):
        source += "\n"
    return banner() + source


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="vendor_bragi")
    parser.add_argument(
        "--upstream",
        type=Path,
        help="the installed Corsair_Bragi_Device.js, found automatically by default",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="report whether the fork is up to date without writing it",
    )
    parser.add_argument(
        "--install",
        action="store_true",
        help="also copy the fork into SignalRGB's own plugin folder",
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="remove the installed copy and leave SignalRGB stock",
    )
    args = parser.parse_args(argv)

    if args.uninstall:
        target = install_target()
        if target is None:
            print("no installed SignalRGB found", file=sys.stderr)
            return 2
        if target.is_file():
            target.unlink()
            print(f"removed  {target}")
        else:
            print(f"not installed  {target}")
        print("restart SignalRGB to go back to its own Corsair plugin")
        return 0

    upstream = args.upstream or find_upstream()
    if upstream is None or not upstream.is_file():
        print(
            "no installed Corsair_Bragi_Device.js found; pass --upstream",
            file=sys.stderr,
        )
        return 2

    wanted = render(upstream)
    current = (
        FORK.read_text(encoding="utf-8").replace("\r\n", "\n")
        if FORK.is_file()
        else None
    )
    relative = FORK.relative_to(REPO_ROOT).as_posix()

    if current != wanted:
        if args.check:
            state = "differs" if current is not None else "missing"
            print(
                f"{state}  {relative}; run tools/vendor_bragi.py to regenerate",
                file=sys.stderr,
            )
            return 1
        FORK.write_bytes(wanted.encode("utf-8"))
        print(f"{'written' if current is not None else 'created'}  {relative}")
    else:
        print(f"unchanged  {relative}  (from {upstream})")

    if not args.install:
        return 0

    target = install_target()
    if target is None:
        print("no installed SignalRGB found to install into", file=sys.stderr)
        return 2

    installed = (
        target.read_text(encoding="utf-8").replace("\r\n", "\n")
        if target.is_file()
        else None
    )
    if installed == wanted:
        print(f"unchanged  {target}")
        return 0

    target.write_bytes(wanted.encode("utf-8"))
    print(f"{'updated' if installed is not None else 'installed'}  {target}")
    print("restart SignalRGB for it to take over the Slipstream dongle")
    return 0


if __name__ == "__main__":
    sys.exit(main())
